### ISSUE TITLE
Don't Work on Edge Tx

### ISSUE THREAD

**Issue by VSemedo** [GilDev/TaraniTunes#18]
Hello again 😁

Four years later I'm switching radio from qx7s to a Jumper T20.

After some hours I finally transfer everything, but your awesome jukebox don't work 😭

I can see the switchs work and I can play the songs individually, but in the telemetry screen when I select a song don't do nothing and the songs don't change if I select random whit the switch.

Maybe you have the time to explain me how to solve it after this 4 years of using and pass along your program. 

Many thanks in advance and Happy Easter

**Comment by jrwieland** [comment]
This has been updated to a newer version 5 years ago.  The old verrsion still works with OpenTX (no development since the devs moved to EdgeTX)
The current version of the player is TaraniTunes-v4.x
This version works with with the current stable version of EdgeTX 2.9 as well as the OpenTX (seperate folders)

The latest version can be found here
https://github.com/jrwieland/TaraniTunes-v4.x

**Comment by GilDev** [comment]
Hi,

Indeed, @jrwieland explained everything well! Thanks again for continuing the development on this, I’m happy to see that some people are still using it. 🙂

Cheers!
